--liquibase formatted sql

--changeset makarov:1
CREATE TABLE notification_tasks(
    id bigint generated by default as IDENTITY primary key,
    chat_id bigint NOT NULL ,
    message TEXT NOT NULL ,
    notification_datetime TIMESTAMP NOT NULL
)